import copy
from . import tool_schemas

def get_openai_tool_schema(tool_name: str):
    """
    Converts a tool definition from our PRD format to the OpenAI API format.

    This function does two key things:
    1. It wraps the tool definition in the required OpenAI structure.
    2. It removes the 'context' parameter from the schema, as this is handled
       by the orchestrator and should not be generated by the LLM.
    """
    if tool_name not in tool_schemas.TOOLS_PRD:
        raise ValueError(f"Tool '{tool_name}' not found in tool definitions.")

    prd_def = tool_schemas.TOOLS_PRD[tool_name]

    # Deep copy to avoid modifying the original schema
    params_schema = copy.deepcopy(prd_def["args_schema"])

    # Remove 'context' from properties if it exists
    if "context" in params_schema.get("properties", {}):
        del params_schema["properties"]["context"]

    # Remove 'context' from required list if it exists
    if "context" in params_schema.get("required", []):
        params_schema["required"].remove("context")

    # Format for OpenAI API
    openai_schema = {
        "type": "function",
        "function": {
            "name": tool_name,
            "description": prd_def["description"],
            "parameters": params_schema,
        },
    }

    return openai_schema
