import copy
from . import tool_schemas

def get_openai_tool_schema(tool_name: str):
    """
    Converts a tool definition from our PRD format to the OpenAI API format.

    This function does two key things:
    1. It wraps the tool definition in the required OpenAI structure.
    2. It removes the 'context' parameter from the schema, as this is handled
       by the orchestrator and should not be generated by the LLM.
    """
    if tool_name not in tool_schemas.TOOLS_PRD:
        raise ValueError(f"Tool '{tool_name}' not found in tool definitions.")

    prd_def = tool_schemas.TOOLS_PRD[tool_name]

    # Deep copy to avoid modifying the original schema
    params_schema = copy.deepcopy(prd_def["args_schema"])

    # Remove 'context' from properties if it exists
    if "context" in params_schema.get("properties", {}):
        del params_schema["properties"]["context"]

    # Remove 'context' from required list if it exists
    if "context" in params_schema.get("required", []):
        params_schema["required"].remove("context")

    # Format for OpenAI API
    openai_schema = {
        "type": "function",
        "function": {
            "name": tool_name,
            "description": prd_def["description"],
            "parameters": params_schema,
        },
    }

    return openai_schema

def parse_llm_response(response_message, primary_tool_name, primary_tool_arg_keys, allow_empty_response=False):
    """
    Parses the LLM response, handling formal tool calls, raw JSON, and valid empty responses.

    Args:
        response_message: The message object from the OpenAI API response.
        primary_tool_name: The name of the agent's main tool (e.g., 'write_beats').
        primary_tool_arg_keys: A list of top-level keys expected in the tool's args.
        allow_empty_response: If True, an empty response is considered a valid "no-op".

    Returns:
        A tuple of (tool_name, function_args). Returns (None, None) for a valid no-op.
    """
    import json

    tool_calls = response_message.tool_calls
    llm_content = response_message.content

    if tool_calls:
        # Ideal case: A formal tool call was made.
        tool_call = tool_calls[0]
        tool_name = tool_call.function.name
        function_args = json.loads(tool_call.function.arguments)
        print(f"   LLM decided to call '{tool_name}'.")
        return tool_name, function_args

    # Check for empty response
    if not llm_content or llm_content.strip() == "":
        if allow_empty_response:
            print("   LLM returned a valid empty response (no-op).")
            return None, None
        else:
            print("   LLM returned an unexpected empty response.")
            raise ValueError("LLM returned an empty response where output was required.")

    # Fallback case: The LLM might have returned raw JSON in the content.
    print("   LLM did not make a formal tool call. Checking content for raw JSON...")
    try:
        # Find the start and end of the JSON object
        start_index = llm_content.find('{')
        end_index = llm_content.rfind('}')

        if start_index != -1 and end_index != -1 and end_index > start_index:
            json_str = llm_content[start_index:end_index+1]
            potential_args = json.loads(json_str)

            # Heuristic check: does this JSON look like our tool's arguments?
            if isinstance(potential_args, dict) and all(key in potential_args for key in primary_tool_arg_keys):
                print(f"   LLM returned raw JSON matching the structure for '{primary_tool_name}'.")
                return primary_tool_name, potential_args
            else:
                print(f"LLM returned unexpected JSON content:\n{llm_content}")
                raise ValueError("LLM returned JSON that does not match expected tool arguments.")
        else:
            # Could not find a JSON object in the content
            raise json.JSONDecodeError("No JSON object found", llm_content, 0)

    except (json.JSONDecodeError, TypeError):
        # It's not valid JSON, it's just prose.
        print(f"LLM did not call a tool or return valid JSON. Response content:\n{llm_content}")
        raise ValueError("LLM was expected to call a tool or return tool arguments as JSON, but did not.")
